{{- $password := required "secrets.postgresPassword must be provided" .Values.secrets.postgresPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secret
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ $password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:%v/%s" .Values.postgres.username $password (include "taskflow.fullname" .) .Values.postgres.port .Values.postgres.database | quote }}
